InsuranceDatabase/Controllers/BrokersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InsuranceDatabase;
using Microsoft.AspNetCore.Authorization;

namespace InsuranceDatabase.Controllers
{
    [Authorize(Roles = "admin,broker")] 
    public class BrokersController : Controller
    {
        private readonly InsuranceContext _context;

        public BrokersController(InsuranceContext context)
        {
            _context = context;
        }

        // GET: Brokers
        public async Task<IActionResult> Index( )
        {
            
            return View(await _context.Brokers.ToListAsync());
        }

        // GET: Brokers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewBag.BrokerName = _context.Brokers.Find(id).FullName;
            var brokers = await _context.Brokers
                .FirstOrDefaultAsync(m => m.Id == id);
           
            if (brokers == null)
            {
                return NotFound();
            }

            var brokerId = id;
            ViewBag.BrokerId = id;
            ViewBag.Day = _context.Brokers.Find(id).BirthDate.Day;
            ViewBag.Month = _context.Brokers.Find(id).BirthDate.Month;
            ViewBag.Year = _context.Brokers.Find(id).BirthDate.Year;
            ViewBag.Count = _context.BrokersCategories.Where(b => b.BrokerId == brokerId).Include(b => b.Category).Count();
            ViewBag.CategoriesList = _context.BrokersCategories.Where(b => b.BrokerId == brokerId).Include(b => b.Category).ToList();
            return View(brokers);
        }

        // GET: Brokers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Brokers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Surname,BirthDate,PhoneNum,Passport,Email,Password")] Brokers brokers)
        {
            
            if (ModelState.IsValid)
            {
                _context.Add(brokers);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(brokers);
        }

        // GET: Brokers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
           
            if (id == null)
            {
                return NotFound();
            }

            var brokers = await _context.Brokers.FindAsync(id);
            if (brokers == null)
            {
                return NotFound();
            }
            return View(brokers);
        }

        // POST: Brokers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Surname,BirthDate,PhoneNum,Passport,Email,Password")] Brokers brokers)
        {
            
            if (id != brokers.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(brokers);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BrokersExists(brokers.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(brokers);
        }

        // GET: Brokers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewBag.BrokerName = _context.Brokers.Find(id).FullName;
            var brokers = await _context.Brokers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (brokers == null)
            {
                return NotFound();
            }

            return View(brokers);
        }

        // POST: Brokers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var brokers = await _context.Brokers.FindAsync(id);
            var docs = _context.Documents.Where(b => b.BrokerId== id).ToList();
            foreach (var doc in docs)
            {
                _context.Documents.Remove(doc);
            }
            _context.Brokers.Remove(brokers);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> BrokersDocuments(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            
            var BrokerId = id;
            ViewBag.BrokerId = id;

            return RedirectToAction("Index", "Documents", new { brokerId = BrokerId } );
        }

        public IActionResult PhoneValid(string? PhoneNum)
        {
            if (PhoneNum != null)
            {
                if (PhoneNum.Length != 10) return Json(data: "Номер телефону занадто которкий");
                for (int i = 0; i < PhoneNum.Length; i++)
                {
                    if (PhoneNum[0] != '0' || PhoneNum[i] < '0' || PhoneNum[i] > '9')
                    {
                        return Json(data: "Невірний формат данних");
                    }
                }
            }
            return Json(data: true);
        }
            public IActionResult PassportValid(string? Passport, int? Id)
            {
                if (Passport != null)
                {
                    if (Passport.Length != 9) return Json(data: "Номер паспорту занадто которкий");
                    for (int i = 0; i < Passport.Length; i++)
                    {
                        if (Passport[i] < '0' || Passport[i] > '9')
                        {
                            return Json(data: "Невірний формат данних");
                        }
                    }

                    var pas = _context.Brokers.Where(b => b.Passport == Passport).Where(b => b.Id != Id);
                    if (pas.Count() > 0) { return Json(data: "Людина з таким номером паспорта вже зареєстрована в базі"); }
                
            }
               
                return Json(data: true);

            }
        public IActionResult NameValid(string? Name)
        {
            if(Name != null)
            {
                if(Name.Length < 2) { return  Json (data: "Невірний формат данних"); }
                for(int i =0; i < Name.Length; i++)
                {
                    if ((Name[i] < 'А' || Name[i] > 'ї')&& Name[i]!='І' ) { return Json(data: "Невірний формат данних"); }
                }
            }
            return Json(data: true);
        }
        public IActionResult SurnameValid(string? Surname)
        {
            if (Surname != null)
            {
                if (Surname.Length < 2) {return Json (data: "Невірний формат данних"); }
                for (int i = 0; i < Surname.Length; i++)
                {
                    if ((Surname[i] < 'А' || Surname[i] > 'ї') && Surname[i] != 'І') { return Json(data: "Невірний формат данних"); }
                }
            }
            return Json(data: true);
        }

        public IActionResult DateValid(DateTime? BirthDate)
        {
            char[] param = { '.', '/', ':',' '};
            string birthDate = BirthDate.ToString();
            int year;
            try {  year = Convert.ToInt32(birthDate.Split(param)[2]); }
            catch (Exception e) { return Json(data: "Невірний формат данних"); }
            if (birthDate != null)
            {
                if (year < DateTime.Today.Year -65 || year > DateTime.Today.Year - 18)
                {
                    return Json(data: "Невірна дата");
                }
            }
             return Json(data: true);

        }

        private bool BrokersExists(int id)
        {
            return _context.Brokers.Any(e => e.Id == id);
        }
    }
}

InsuranceDatabase/Controllers/RolesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LibraryMVC.Models;
using LibraryMVC.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
namespace LibraryMVC.Controllers
{
    [Authorize(Roles = "admin")]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole>_roleManager;
        UserManager<User> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
    public IActionResult Index() => View(_roleManager.Roles.ToList());
    public IActionResult UserList() => View(_userManager.Users.ToList());
    public async Task<IActionResult> Edit(string userId)
    {
        // отримуємо користувача
        User user = await _userManager.FindByIdAsync(userId);
        if (user != null)
        {
            //список ролей користувача
            var userRoles = await _userManager.GetRolesAsync(user);
            var allRoles = _roleManager.Roles.ToList();
            ChangeRoleViewModel model = new ChangeRoleViewModel
            {
                UserId = user.Id,
                UserEmail = user.Email,
                UserRoles = userRoles,
                AllRoles = allRoles
            };
            return View(model);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string>roles)
        {
            // отримуємо користувача
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // список ролей користувача
                var userRoles = await _userManager.GetRolesAsync(user);
        // получаем все роли
        var allRoles = _roleManager.Roles.ToList();
        // список ролей, які було додано
        var addedRoles = roles.Except(userRoles);
        // список ролей, які було видалено
        var removedRoles = userRoles.Except(roles);
        await _userManager.AddToRolesAsync(user, addedRoles);
        await _userManager.RemoveFromRolesAsync(user, removedRoles);
                return RedirectToAction("UserList");
            }
            return NotFound();
        }
        public IActionResult Create() => View();
        [HttpPost]

        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }




    }
}

InsuranceDatabase/Controllers/UsersController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using LibraryMVC.Models;
using LibraryMVC.ViewModel;
using LibraryMVC.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace LibraryMVC.Controllers
{
    [Authorize(Roles = "admin")]
    public class UsersController : Controller
    {
        UserManager<User> _userManager;

        public UsersController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index() => View(_userManager.Users.ToList());

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User { Email = model.Email, UserName = model.Email, Year = model.Year };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel { Id = user.Id, Email = user.Email, Year = user.Year };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;
                    user.Year = model.Year;

                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> ChangePassword(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ChangePasswordViewModel model = new ChangePasswordViewModel { Id = user.Id, Email = user.Email };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    IdentityResult result =
                        await _userManager.ChangePasswordAsync(user, model.OldPassword, model.NewPassword);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Такого користувача немає в базі");
                }
            }
            return View(model);
        }


    }
}

InsuranceDatabase/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<globalization culture="en-US" uiCulture="en" />

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InsuranceDatabase</title>



    <link href="~/lib/bootstrap/dist/css/bootstrap_flatly.min.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
       


    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InsuranceDatabase</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    @if (User.IsInRole("broker") || User.IsInRole("admin"))
                    {
                    <ul class="navbar-nav mr-auto">

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Categories" asp-action="Index">Категорії<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Brokers" asp-action="Index">Брокери</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Documents" asp-action="Index">Договори</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Clients" asp-action="Index">Клієнти</a>
                        </li>
                        @if (User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Roles" asp-action="Index">Керування ролями</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Users" asp-action="Index">Список користувачів</a>
                            </li>
                        }
                    </ul>
                    }
                    else
                    {
                        <ul class="navbar-nav mr-auto">

                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Categories" asp-action="Index">Категорії<span class="sr-only">(current)</span></a>
                            </li>

                        </ul>
                    }

                    @if (User.Identity.IsAuthenticated)
                    {
                

                        <ul class="navbar-nav">
                            <li><b><@User.Identity.Name></b></li>
                            <li class="nav-item">
                                <form method="post" asp-controller="Account" asp-action="Logout">
                                    <input type="submit" value="Вихід" class="makealink" asp-controller="Account" asp-action="Logout" />
                                    <span class="sr-only">(current)</span>
                                </form>
                            </li>
                        </ul>

                    }
                    else
                    {
                        <ul class="navbar-nav">

                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="Register">Реєстрація<span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="Login">Вхід<span class="sr-only">(current)</span></a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>